#!/bin/bash
# Install a custom Redis version - http://redis.io/
#
# Add at least the following environment variables to your project configuration
# (otherwise the defaults below will be used).
# * REDIS_VERSION
# * REDIS_PORT
#
# Include in your builds via
# \curl -sSL https://raw.githubusercontent.com/dannybster/ci-scripts/master/scripts/install-redis | bash -s
REDIS_VERSION=${REDIS_VERSION:="3.2.4"}
REDIS_PORT=${REDIS_PORT:="6380"}
REDIS_DIR=${MONGODB_DIR:="$HOME/redis"}

set -e
CACHED_DOWNLOAD="${HOME}/cache/redis-linux-x86_64-ubuntu1404-redis-${REDIS_VERSION}.tgz"

mkdir -p "${REDIS_DIR}"
wget --continue --output-document "${CACHED_DOWNLOAD}" "http://download.redis.io/releases/redis-${REDIS_VERSION}.tar.gz"
tar -xaf "${CACHED_DOWNLOAD}" --strip-components=1 --directory "${REDIS_DIR}"
