#!/bin/bash
# Install a custom MongoDB version - https://www.mongodb.org/
#
# Add at least the following environment variables to your project configuration
# (otherwise the defaults below will be used).
# * MONGODB_VERSION
# * MONGODB_PORT
#
# Include in your builds via
# \curl -sSL https://raw.githubusercontent.com/codeship/scripts/master/packages/mongodb.sh | bash -s
MONGODB_VERSION=${MONGODB_VERSION:="3.0.4"}
MONGODB_PORT=${MONGODB_PORT:="27018"}
MONGODB_DIR=${MONGODB_DIR:="$HOME/mongodb"}

set -e
CACHED_DOWNLOAD="${HOME}/cache/mongodb-linux-x86_64-ubuntu1404-${MONGODB_VERSION}.tgz"

mkdir -p "${MONGODB_DIR}"
wget --continue --output-document "${CACHED_DOWNLOAD}" "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1404-${MONGODB_VERSION}.tgz"
tar -xaf "${CACHED_DOWNLOAD}" --strip-components=1 --directory "${MONGODB_DIR}"
